// <auto-generated />
using System;
using Assets.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assets.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20190712181646_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assets.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AllocatedContactId");

                    b.Property<DateTimeOffset?>("AllocatedDate");

                    b.Property<string>("AllocatedUser");

                    b.Property<int>("AssetTypeId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<Guid>("Guid");

                    b.Property<string>("Make")
                        .HasMaxLength(128);

                    b.Property<string>("Model")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128);

                    b.Property<string>("Tag")
                        .HasMaxLength(128);

                    b.Property<int>("TenantId");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id")
                        .HasName("PK_Asset")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Guid")
                        .HasName("AK_Asset_Guid");

                    b.HasIndex("AllocatedContactId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("TenantId", "Guid")
                        .IsUnique()
                        .HasName("IX_Asset_Tenant_Guid");

                    b.HasIndex("TenantId", "Tag")
                        .HasName("IX_Asset_Tenant_Tag");

                    b.ToTable("Asset");
                });

            modelBuilder.Entity("Assets.Entities.AssetAllocationChange", b =>
                {
                    b.Property<int>("AssetId");

                    b.Property<int>("ContactId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("AssetId", "ContactId")
                        .HasName("PK_AssetAllocationChange")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ContactId");

                    b.ToTable("AssetAllocationChange");
                });

            modelBuilder.Entity("Assets.Entities.AssetComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssetId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<Guid>("Guid");

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("PK_AssetComment")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Guid")
                        .HasName("AK_AssetComment_Guid");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetComment");
                });

            modelBuilder.Entity("Assets.Entities.AssetPicture", b =>
                {
                    b.Property<int>("AssetId");

                    b.Property<int>("PictureId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("AssetId", "PictureId")
                        .HasName("PK_AssetPicture")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("AssetPicture");
                });

            modelBuilder.Entity("Assets.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("PK_AssetType")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Name")
                        .HasName("AK_AssetType_Name");

                    b.ToTable("AssetType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Screen"
                        });
                });

            modelBuilder.Entity("Assets.Entities.Blob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .IsRequired();

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<Guid>("Guid");

                    b.HasKey("Id")
                        .HasName("PK_Blob")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Guid")
                        .HasName("AK_Blob_Guid");

                    b.ToTable("Blob");
                });

            modelBuilder.Entity("Assets.Entities.Computer", b =>
                {
                    b.Property<int>("ComputerId");

                    b.Property<long?>("Memory");

                    b.Property<string>("Processor")
                        .HasMaxLength(128);

                    b.HasKey("ComputerId")
                        .HasName("PK_Computer")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Computer");
                });

            modelBuilder.Entity("Assets.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactTypeId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<Guid>("Guid");

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Name");

                    b.Property<int>("TenantId");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id")
                        .HasName("PK_Contact")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Guid")
                        .HasName("AK_Contact_Guid");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("TenantId", "Guid")
                        .IsUnique()
                        .HasName("IX_Contact_Tenant_Guid");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Assets.Entities.ContactComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<Guid>("Guid");

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("PK_ContactComment")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Guid")
                        .HasName("AK_ContactComment_Guid");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactComment");
                });

            modelBuilder.Entity("Assets.Entities.ContactPicture", b =>
                {
                    b.Property<int>("ContactId");

                    b.Property<int>("PictureId");

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("ContactId", "PictureId")
                        .HasName("PK_ContactPicture")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ContactPicture");
                });

            modelBuilder.Entity("Assets.Entities.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("PK_ContactType")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Name")
                        .HasName("AK_ContactType_Name");

                    b.ToTable("ContactType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Person"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organisation"
                        });
                });

            modelBuilder.Entity("Assets.Entities.Phone", b =>
                {
                    b.Property<int>("PhoneId");

                    b.Property<string>("Imei")
                        .HasMaxLength(128);

                    b.Property<long?>("Memory");

                    b.Property<string>("Processor")
                        .HasMaxLength(128);

                    b.HasKey("PhoneId")
                        .HasName("PK_Phone")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("Assets.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id")
                        .HasName("PK_Role")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Name")
                        .HasName("AK_Role_Name");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reader"
                        });
                });

            modelBuilder.Entity("Assets.Entities.Screen", b =>
                {
                    b.Property<int>("ScreenId");

                    b.Property<decimal?>("SizeInches")
                        .HasColumnType("DECIMAL(8, 1)");

                    b.HasKey("ScreenId")
                        .HasName("PK_Screen")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Screen");
                });

            modelBuilder.Entity("Assets.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .IsRequired();

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id")
                        .HasName("PK_Tenant")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("Area")
                        .HasName("AK_Tenant_Area");

                    b.HasAlternateKey("Name")
                        .HasName("AK_Tenant_Name");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("Assets.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("DeletedDate");

                    b.Property<string>("DeletedUser")
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .HasMaxLength(128);

                    b.Property<string>("FullName")
                        .HasMaxLength(128);

                    b.Property<string>("Initials")
                        .HasMaxLength(128);

                    b.Property<DateTimeOffset?>("LastAccessedDate");

                    b.Property<DateTimeOffset>("ModifiedDate");

                    b.Property<string>("ModifiedUser")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Phone")
                        .HasMaxLength(128);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id")
                        .HasName("PK_User")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasAlternateKey("UserName")
                        .HasName("AK_User_UserName");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Assets.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRole")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Assets.Entities.UserTenantRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("TenantId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "TenantId", "RoleId")
                        .HasName("PK_UserTenantRole")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("RoleId");

                    b.ToTable("UserTenantRole");
                });

            modelBuilder.Entity("Assets.Entities.Asset", b =>
                {
                    b.HasOne("Assets.Entities.Contact", "AllocatedContact")
                        .WithMany("Assets")
                        .HasForeignKey("AllocatedContactId")
                        .HasConstraintName("FK_Asset_AllocatedContact")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Assets.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .HasConstraintName("FK_Asset_AssetType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.Tenant", "Tenant")
                        .WithMany("Assets")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_Asset_Tenant")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assets.Entities.AssetAllocationChange", b =>
                {
                    b.HasOne("Assets.Entities.Asset", "Asset")
                        .WithMany("AllocationChanges")
                        .HasForeignKey("AssetId")
                        .HasConstraintName("FK_AssetAllocationChange_Asset")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK_AssetAllocationChange_Contact")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.AssetComment", b =>
                {
                    b.HasOne("Assets.Entities.Asset", "Asset")
                        .WithMany("Comments")
                        .HasForeignKey("AssetId")
                        .HasConstraintName("FK_AssetComment_Asset")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.AssetPicture", b =>
                {
                    b.HasOne("Assets.Entities.Asset", "Asset")
                        .WithMany("Pictures")
                        .HasForeignKey("AssetId")
                        .HasConstraintName("FK_AssetPicture_Asset")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.Blob", "Picture")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .HasConstraintName("FK_AssetPicture_Blob")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.Computer", b =>
                {
                    b.HasOne("Assets.Entities.Asset", "Asset")
                        .WithOne("Computer")
                        .HasForeignKey("Assets.Entities.Computer", "ComputerId")
                        .HasConstraintName("FK_Computer_Asset")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.Contact", b =>
                {
                    b.HasOne("Assets.Entities.ContactType", "ContactType")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactTypeId")
                        .HasConstraintName("FK_Contact_ContactType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.Tenant", "Tenant")
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId")
                        .HasConstraintName("FK_Contact_Tenant")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.ContactComment", b =>
                {
                    b.HasOne("Assets.Entities.Contact", "Contact")
                        .WithMany("Comments")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK_ContactComment_Contact")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.ContactPicture", b =>
                {
                    b.HasOne("Assets.Entities.Blob", "Picture")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK_ContactPicture_Blob")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.Contact", "Contact")
                        .WithMany("Pictures")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("FK_ContactPicture_Contact")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.Phone", b =>
                {
                    b.HasOne("Assets.Entities.Asset", "Asset")
                        .WithOne("Phone")
                        .HasForeignKey("Assets.Entities.Phone", "PhoneId")
                        .HasConstraintName("FK_Phone_Asset")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.Screen", b =>
                {
                    b.HasOne("Assets.Entities.Asset", "Asset")
                        .WithOne("Screen")
                        .HasForeignKey("Assets.Entities.Screen", "ScreenId")
                        .HasConstraintName("FK_Screen_Asset")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.UserRole", b =>
                {
                    b.HasOne("Assets.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_UserRole_Role")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserRole_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assets.Entities.UserTenantRole", b =>
                {
                    b.HasOne("Assets.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_UserTenantRole_Role")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserTenantRole_Tenant")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assets.Entities.User", "User")
                        .WithMany("TenantRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserTenantRole_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
